import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    'functions/**',
    // Generated by Netlify tooling / local experiments; not part of source.
    '.tmp-netlify-index.js',
    // Legacy/backup pages kept for reference; not shipped as active routes.
    '**/*_old.jsx',
    '**/*_backup.jsx',
  ]),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z_]' }],
      // This repo exports hooks/helpers from context files; Fast Refresh rule is too strict here.
      'react-refresh/only-export-components': 'off',
      // We intentionally initialise some state from effects for UX (modals, remote data).
      'react-hooks/set-state-in-effect': 'off',
    },
  },
])
